[project]
name = "sssp"
version = "0.1.0"
requires-python = ">=3.13.4"
dependencies = [
    "black>=25.9.0",
    "coverage>=7.10.6",
    "pytest>=8.4.2",
]


[project.scripts]
quranllm = "sssp.main:main"


[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"
